apiVersion: v1
kind: Service
metadata:
  name: youtrack
spec:
  ports:
  - port: 8080
  selector:
    app: youtrack
  type: LoadBalancer
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: youtrack-deployment
  labels:
    app: youtrack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: youtrack
  template:
    metadata:
      labels:
        app: youtrack
    spec:
      containers:
      - name: youtrack
        image: jetbrains/youtrack:2018.1.40341
        ports:
        - name: youtrack-port
          containerPort: 8080
