apiVersion: v1
kind: Pod
metadata:
  name: sample-emptydir
spec:
  containers:
  - name: nginx-container
    image: nginx:1.12
    volumeMounts:
    - mountPath: /cache
      name: cache-volume
  volumes:
  - name: cache-volume
    emptyDir: {}

