apiVersion: v1
kind: Pod
metadata:
  name: sample-env-fail3
spec:
  containers:
    - name: nginx-container
      image: nginx:1.12
      command: ["echo"]
      args: ["$(K8S_NODE)", "${K8S_NODE}"]
      env:
        - name: K8S_NODE
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName

