apiVersion: v1
kind: Pod
metadata:
  name: sample-configmap-multi-env
spec:
  containers:
    - name: sample-configmap-multi-env
      image: nginx:1.12
      envFrom:
        - configMapRef:
            name: sample-configmap

